[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install --no-package-lock --include=dev --legacy-peer-deps"
]

[phases.build]
cmds = ["node ./build.mjs"]

[start]
cmd = "node --enable-source-maps ./dist/index.mjs"
