// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/VideoTemplate.tsx": () => import("../components/mockups/VideoTemplate.tsx"),
  "./components/mockups/dev-bio.tsx": () => import("../components/mockups/dev-bio.tsx"),
  "./components/mockups/facebook-poster.tsx": () => import("../components/mockups/facebook-poster.tsx"),
  "./components/mockups/google-play-scene.tsx": () => import("../components/mockups/google-play-scene.tsx"),
  "./components/mockups/hasahisawi-poster-4k.tsx": () => import("../components/mockups/hasahisawi-poster-4k.tsx"),
  "./components/mockups/hasahisawi-poster.tsx": () => import("../components/mockups/hasahisawi-poster.tsx"),
  "./components/mockups/hasahisawi-video.tsx": () => import("../components/mockups/hasahisawi-video.tsx"),
  "./components/mockups/promotional-ad.tsx": () => import("../components/mockups/promotional-ad.tsx"),
  "./components/mockups/status-poster.tsx": () => import("../components/mockups/status-poster.tsx"),
  "./components/mockups/update-post-4k.tsx": () => import("../components/mockups/update-post-4k.tsx"),
  "./components/mockups/update-post-v2-4k.tsx": () => import("../components/mockups/update-post-v2-4k.tsx"),
  "./components/mockups/update-post-v2.tsx": () => import("../components/mockups/update-post-v2.tsx"),
  "./components/mockups/update-post.tsx": () => import("../components/mockups/update-post.tsx"),
  "./components/mockups/whatsapp-status.tsx": () => import("../components/mockups/whatsapp-status.tsx")
};
