// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/VideoTemplate.tsx": () => import("../components/mockups/VideoTemplate.tsx"),
  "./components/mockups/facebook-poster.tsx": () => import("../components/mockups/facebook-poster.tsx"),
  "./components/mockups/google-play-scene.tsx": () => import("../components/mockups/google-play-scene.tsx"),
  "./components/mockups/hasahisawi-video.tsx": () => import("../components/mockups/hasahisawi-video.tsx"),
  "./components/mockups/whatsapp-status.tsx": () => import("../components/mockups/whatsapp-status.tsx")
};
